<?php
/**
 * Field groups that are not block layouts — the CPTs and the options page.
 *
 * Returned to lp_all_field_groups() in acf-build.php, which assigns keys and
 * writes the JSON. Field shapes are taken from the Storybook components that
 * consume them, so a record carries exactly what the blocks project from.
 *
 * @package londonparkour_v8
 */

defined( 'ABSPATH' ) || exit;

/**
 * Location rule helper.
 *
 * @param string $param    Rule param, e.g. 'post_type'.
 * @param string $value    Rule value.
 * @return array
 */
$lp_where = static function ( string $param, string $value ): array {
	return array( array( array( 'param' => $param, 'operator' => '==', 'value' => $value ) ) );
};

return array(

	/* ── Classes ─────────────────────────────────────────────────────────
	 * Feeds the Hero board (time/title/location/spaces), the Classes board
	 * (the full eleven-column projection) and the CTA session panel.
	 * A session is a time-slot of a class, held here rather than as its own
	 * post type — see the note in app/setup/cpt.php.
	 */
	array(
		'key'            => 'group_lp_class',
		'title'          => __( 'Class', 'londonparkour_v8' ),
		'location'       => $lp_where( 'post_type', 'lp_class' ),
		'menu_order'     => 0,
		'position'       => 'normal',
		'style'          => 'default',
		'label_placement' => 'top',
		'active'         => true,
		'description'    => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'         => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'subtitle',
				'label'        => __( 'Subtitle', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "60 min · all kit provided"', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'location',
				'label'         => __( 'Location', 'londonparkour_v8' ),
				'type'          => 'post_object',
				'post_type'     => array( 'lp_location' ),
				'return_format' => 'id',
			),
			array(
				'name'          => 'coaches',
				'label'         => __( 'Coaches', 'londonparkour_v8' ),
				'type'          => 'relationship',
				'post_type'     => array( 'lp_coach' ),
				'return_format' => 'id',
				'filters'       => array( 'search' ),
			),
			/*
			 * Mirrors `is_lead` on Coach and `is_flagship` on Location, for the
			 * same reason: the Classes archive features one class above the
			 * grid and then lists the rest, so the grid query has to know which
			 * one is already on show or it appears twice. No ordering picks it
			 * — the design's featured class is neither first nor newest — so it
			 * has to be a flag. See PORT-FINDINGS §13.
			 */
			array(
				'name'          => 'is_featured',
				'label'         => __( 'Featured class', 'londonparkour_v8' ),
				'type'          => 'true_false',
				'ui'            => 1,
				'default_value' => 0,
				'instructions'  => __( 'Shown above the Classes grid, and left out of it.', 'londonparkour_v8' ),
			),

			lp_tab( __( 'Items', 'londonparkour_v8' ) ),
			array(
				'name'         => 'sessions',
				'label'        => __( 'Sessions', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'table',
				'button_label' => __( 'Add session', 'londonparkour_v8' ),
				'instructions' => __( 'Each recurring time-slot of this class. These are the rows on the timetable boards.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					/*
					 * The real date this session runs. `date_label` beside it is
					 * the BOARD label ("TODAY", "THU") the departure boards
					 * print — a different thing, and not a date: it cannot be
					 * compared to a week window, which is what the Agenda page
					 * needs. See PORT-FINDINGS §20.
					 */
					array(
						'name'           => 'date',
						'label'          => __( 'Date', 'londonparkour_v8' ),
						'type'           => 'date_picker',
						'display_format' => 'D j M Y',
						'return_format'  => 'Y-m-d',
						'first_day'      => 1,
						'instructions'   => __( 'The day this session runs. Drives the Agenda board.', 'londonparkour_v8' ),
					),
					array(
						'name'         => 'date_label',
						'label'        => __( 'Board label', 'londonparkour_v8' ),
						'type'         => 'text',
						'instructions' => __( 'What the departure boards print, e.g. "TODAY". Not a date.', 'londonparkour_v8' ),
					),
					array(
						'name'  => 'time',
						'label' => __( 'Time', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'  => 'spaces',
						'label' => __( 'Spaces', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'          => 'sold_out',
						'label'         => __( 'Sold out', 'londonparkour_v8' ),
						'type'          => 'true_false',
						'ui'            => 1,
						'default_value' => 0,
					),
				),
			),

			lp_tab( __( 'Actions', 'londonparkour_v8' ) ),
			array(
				'name'          => 'price',
				'label'         => __( 'Price', 'londonparkour_v8' ),
				'type'          => 'text',
			),
			array(
				'name'          => 'price_label',
				'label'         => __( 'Price label', 'londonparkour_v8' ),
				'type'          => 'text',
				'default_value' => 'DROP-IN',
			),
			lp_field_action( 'primary_action', __( 'Primary action', 'londonparkour_v8' ) ),
		),
	),

	/* ── Coaches ─────────────────────────────────────────────────────────
	 * Feeds the Coaches block: one lead coach (portrait + quote) and a roster
	 * of thumbnails. Name is the post title; portrait is the featured image.
	 */
	array(
		'key'             => 'group_lp_coach',
		'title'           => __( 'Coach', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_coach' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'role',
				'label'        => __( 'Role', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "HEAD COACH / 11 YRS"', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'specialty',
				'label'        => __( 'Specialty', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "Precision & balance"', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'location',
				'label'         => __( 'Location', 'londonparkour_v8' ),
				'type'          => 'post_object',
				'post_type'     => array( 'lp_location' ),
				'return_format' => 'id',
				'allow_null'    => 1,
			),
			array(
				'name'         => 'quote',
				'label'        => __( 'Quote', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'Shown only when this coach leads the Coaches block.', 'londonparkour_v8' ),
			),
			/*
			 * Mirrors `is_flagship` on Location, and for the same reason: the
			 * Coaches block features one coach separately and then lists the
			 * roster, so the roster query has to know who is already on show.
			 * Without it the lead appears twice. See PORT-FINDINGS §13.
			 */
			array(
				'name'          => 'is_lead',
				'label'         => __( 'Lead coach', 'londonparkour_v8' ),
				'type'          => 'true_false',
				'ui'            => 1,
				'default_value' => 0,
				'instructions'  => __( 'Featured above the roster, and left out of it.', 'londonparkour_v8' ),
			),
		),
	),

	/* ── Locations ───────────────────────────────────────────────────────
	 * Feeds the Locations block (flagship card + site list) and TrainInPerson
	 * (kicker/title/detail). Same record, two projections.
	 */
	array(
		'key'             => 'group_lp_location',
		'title'           => __( 'Location', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_location' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			lp_field_eyebrow(
				array(
					'name'         => 'tag',
					'label'        => __( 'Tag', 'londonparkour_v8' ),
					'instructions' => __( 'e.g. "FLAGSHIP INDOOR SITE"', 'londonparkour_v8' ),
				)
			),
			array(
				'name'         => 'meta',
				'label'        => __( 'Meta', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "SW8 1SR · 4 MIN FROM VAUXHALL · OPEN 07:00–22:00"', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'type',
				'label'         => __( 'Type', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'choices'       => array(
					'INDOOR'  => __( 'Indoor', 'londonparkour_v8' ),
					'OUTDOOR' => __( 'Outdoor', 'londonparkour_v8' ),
				),
				'default_value' => 'INDOOR',
			),
			array(
				'name'          => 'is_flagship',
				'label'         => __( 'Flagship site', 'londonparkour_v8' ),
				'type'          => 'true_false',
				'ui'            => 1,
				'default_value' => 0,
			),
			array(
				'name'  => 'latitude',
				'label' => __( 'Latitude', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'  => 'longitude',
				'label' => __( 'Longitude', 'londonparkour_v8' ),
				'type'  => 'text',
			),
		),
	),

	/* ── Tutorials ───────────────────────────────────────────────────────
	 * Feeds TutorialsIndex / TutorialsSeries / TutorialDetail.
	 */
	array(
		'key'             => 'group_lp_tutorial',
		'title'           => __( 'Tutorial', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_tutorial' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'duration',
				'label'        => __( 'Duration', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "8:24"', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'video_url',
				'label'         => __( 'Video URL', 'londonparkour_v8' ),
				'type'          => 'url',
			),
			array(
				'name'          => 'coaches',
				'label'         => __( 'Coaches', 'londonparkour_v8' ),
				'type'          => 'relationship',
				'post_type'     => array( 'lp_coach' ),
				'return_format' => 'id',
				'filters'       => array( 'search' ),
			),
		),
	),

	/* ── Legal ───────────────────────────────────────────────────────────
	 * Feeds templates/legal.php. Doc facts, doc actions and the ten clauses
	 * are structured because the body's "ON THIS PAGE" index rail is keyed to
	 * clause numbers and jumps to per-clause ids — the Storybook source itself
	 * says this list is prose furniture, not a ListRow, but it still has to be
	 * data, not the_content(). Copy defaults (the ten clauses' own text, the
	 * doc facts, the doc actions, the pager labels) live in templates/legal.php
	 * as $args fallbacks, taken verbatim from Legal.js's own DOC_FACTS /
	 * DOC_ACTIONS / CLAUSES constants — never here.
	 *
	 * `prev` / `next` are bare ACF Link fields, not the lp_field_action()
	 * group: the source's own pager points at a Privacy and a Cookie policy
	 * that exist in neither the design nor this repo, so an editor sets the
	 * link only once real pages exist. Until then the template falls back to
	 * the source's labels with no href, exactly as the port brief requires.
	 */
	array(
		'key'             => 'group_lp_legal',
		'title'           => __( 'Legal', 'londonparkour_v8' ),
		'location'        => $lp_where( 'page_template', 'templates/legal.php' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Items', 'londonparkour_v8' ) ),
			array(
				'name'         => 'doc_facts',
				'label'        => __( 'Doc facts', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'table',
				'button_label' => __( 'Add fact', 'londonparkour_v8' ),
				'instructions' => __( 'e.g. "EFFECTIVE" / "1 April 2026". Shown left of the doc-meta rule.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'label',
						'label' => __( 'Label', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'  => 'value',
						'label' => __( 'Value', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'         => 'clauses',
				'label'        => __( 'Clauses', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add clause', 'londonparkour_v8' ),
				'instructions' => __( 'Each becomes a numbered heading in the body and a row in the "On this page" index.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'         => 'number',
						'label'        => __( 'Number', 'londonparkour_v8' ),
						'type'         => 'text',
						'instructions' => __( 'e.g. "01"', 'londonparkour_v8' ),
					),
					array(
						'name'  => 'title',
						'label' => __( 'Title', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'         => 'paragraphs',
						'label'        => __( 'Paragraphs', 'londonparkour_v8' ),
						'type'         => 'repeater',
						'layout'       => 'table',
						'button_label' => __( 'Add paragraph', 'londonparkour_v8' ),
						'sub_fields'   => array(
							array(
								'name'      => 'text',
								'label'     => __( 'Paragraph', 'londonparkour_v8' ),
								'type'      => 'textarea',
								'rows'      => 3,
								'new_lines' => '',
							),
						),
					),
				),
			),

			lp_tab( __( 'Actions', 'londonparkour_v8' ) ),
			array(
				'name'         => 'doc_actions',
				'label'        => __( 'Doc actions', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'table',
				'button_label' => __( 'Add action', 'londonparkour_v8' ),
				'instructions' => __( 'e.g. "DOWNLOAD PDF ↓". Right of the doc-meta rule; not yet linked to a real destination.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'label',
						'label' => __( 'Label', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'          => 'prev',
				'label'         => __( 'Previous page', 'londonparkour_v8' ),
				'type'          => 'link',
				'return_format' => 'array',
				'instructions'  => __( 'The link text is the pager label. Leave empty to show the default label with no link.', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'next',
				'label'         => __( 'Next page', 'londonparkour_v8' ),
				'type'          => 'link',
				'return_format' => 'array',
				'instructions'  => __( 'The link text is the pager label. Leave empty to show the default label with no link.', 'londonparkour_v8' ),
			),
		),
	),

	/* ── Post (native blog) ──────────────────────────────────────────────
	 * Feeds home.php (BlogIndex) and single.php (BlogDetail). Title, excerpt,
	 * publish date, featured image and category are all native and read
	 * directly in both templates — this group holds only what WordPress does
	 * not already store. `read_time` is shared by both (the same post's meta
	 * line on the index card and the detail page). The body is TWO
	 * repeaters — `body_sections` before the pull-quote, `body_sections_
	 * after_quote` after it — matching BlogDetail.js's own DEFAULT_BODY shape
	 * exactly (`sections` / `sectionsAfterQuote`). single.php derives the
	 * "IN THIS ARTICLE" TOC and each heading's anchor id from these two
	 * repeaters — never stored a third time.
	 */
	array(
		'key'             => 'group_lp_post',
		'title'           => __( 'Blog', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'post' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'read_time',
				'label'        => __( 'Read time', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "3 MIN READ". Shown on the blog index card and the article meta line.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'standfirst',
				'label'        => __( 'Standfirst', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 2,
				'new_lines'    => '',
				'instructions' => __( 'The intro line under the article title. Separate from the excerpt, which is what the blog index card shows.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'author_role',
				'label'        => __( 'Author role', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "HEAD COACH". Shown next to the author name.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'caption_location',
				'label'        => __( 'Photo location', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "IMPERIAL COLLEGE LONDON · SOUTH KENSINGTON". Left side of the caption band under the hero photo.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'caption_credit',
				'label'        => __( 'Photo credit', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "PHOTO: LONDONPARKOUR". Right side of the caption band.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'body_intro',
				'label'        => __( 'Body intro', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'The first paragraph of the article body, before the first heading.', 'londonparkour_v8' ),
			),

			lp_tab( __( 'Items', 'londonparkour_v8' ) ),
			array(
				'name'         => 'body_sections',
				'label'        => __( 'Body sections', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add section', 'londonparkour_v8' ),
				'instructions' => __( 'Sections before the pull-quote. Each becomes an H3 in the article and a row in the "In this article" index — its anchor id is derived from the heading.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'heading',
						'label' => __( 'Heading', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'      => 'body',
						'label'     => __( 'Body', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 4,
						'new_lines' => '',
					),
				),
			),
			array(
				'name'         => 'pull_quote',
				'label'        => __( 'Pull quote', 'londonparkour_v8' ),
				'type'         => 'group',
				'layout'       => 'block',
				'instructions' => __( 'Sits between the two section groups below.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'      => 'quote',
						'label'     => __( 'Quote', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 2,
						'new_lines' => '',
					),
					array(
						'name'  => 'attribution',
						'label' => __( 'Attribution', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'         => 'body_sections_after_quote',
				'label'        => __( 'Body sections (after quote)', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add section', 'londonparkour_v8' ),
				'instructions' => __( 'Sections after the pull-quote. Same shape as the sections above.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'heading',
						'label' => __( 'Heading', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'      => 'body',
						'label'     => __( 'Body', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 4,
						'new_lines' => '',
					),
				),
			),
		),
	),

	/* ── Site settings ───────────────────────────────────────────────────
	 * The theme is two axes composed into one data-theme value, exactly as the
	 * Storybook toolbar composes it. Read by lp_theme_name().
	 */
	array(
		'key'             => 'group_lp_site_settings',
		'title'           => __( 'Site Settings', 'londonparkour_v8' ),
		'location'        => $lp_where( 'options_page', 'lp-site-settings' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Settings', 'londonparkour_v8' ) ),
			array(
				'name'          => 'theme_ground',
				'label'         => __( 'Ground', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'instructions'  => __( 'The page background family.', 'londonparkour_v8' ),
				'choices'       => array(
					'dark'  => __( 'Dark', 'londonparkour_v8' ),
					'light' => __( 'Light', 'londonparkour_v8' ),
				),
				'default_value' => 'dark',
			),
			array(
				'name'          => 'theme_signal',
				'label'         => __( 'Signal', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'instructions'  => __( 'The single accent colour.', 'londonparkour_v8' ),
				'choices'       => array(
					'yellow' => __( 'Yellow', 'londonparkour_v8' ),
					'green'  => __( 'Green', 'londonparkour_v8' ),
				),
				'default_value' => 'yellow',
			),
		),
	),
);
