<?php
/**
 * `wp lp acf:build` — compose ACF definitions from PHP into acf-json/.
 *
 * Writes:
 *   - Field groups from block fields.php files and app/setup/acf-groups.php
 *   - lp_* post types and taxonomies from app/setup/cpt.php
 *
 * v7-imported field groups, post types, and taxonomies in acf-json/ are
 * preserved (see app/setup/acf-manifest.php). Use `--sync` to import all local
 * JSON into the database so items appear in the ACF admin UI.
 *
 * @package londonparkour_v8
 */

defined( 'ABSPATH' ) || exit;

require_once get_theme_file_path( 'app/setup/acf-manifest.php' );
require_once get_theme_file_path( 'app/setup/acf-cpt-json.php' );
require_once get_theme_file_path( 'app/setup/acf-sync.php' );

/**
 * Collect every block layout by reading blocks/<name>/fields.php.
 *
 * @return array<string, array> Layouts keyed by folder slug.
 */
function lp_collect_block_layouts(): array {
	$layouts = array();

	foreach ( glob( get_theme_file_path( 'blocks/*/fields.php' ) ) ?: array() as $file ) {
		$slug   = basename( dirname( $file ) );
		$layout = require $file;

		if ( ! is_array( $layout ) ) {
			continue;
		}

		$layout['name']  = $layout['name'] ?? str_replace( '-', '_', $slug );
		$layout['label'] = $layout['label'] ?? ucwords( str_replace( '-', ' ', $slug ) );
		$layout['slug']  = $slug;

		$layouts[ $slug ] = $layout;
	}

	ksort( $layouts );

	return $layouts;
}

/**
 * The Page Sections field group — one Flexible Content field whose layouts are
 * the folders under blocks/.
 *
 * @return array
 */
function lp_build_sections_group(): array {
	$layouts = array();

	foreach ( lp_collect_block_layouts() as $slug => $layout ) {
		$layouts[] = array(
			'name'       => $layout['name'],
			'label'      => $layout['label'],
			'display'    => 'block',
			'min'        => '',
			'max'        => '',
			'sub_fields' => $layout['sub_fields'] ?? array(),
		);
	}

	return array(
		'key'                   => 'group_lp_page_sections',
		'title'                 => __( 'Page Sections', 'londonparkour_v8' ),
		'fields'                => array(
			array(
				'name'         => 'page_sections',
				'label'        => __( 'Sections', 'londonparkour_v8' ),
				'type'         => 'flexible_content',
				'button_label' => __( 'Add section', 'londonparkour_v8' ),
				'layouts'      => $layouts,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'hide_on_screen'        => array( 'the_content', 'excerpt', 'custom_fields', 'discussion', 'comments' ),
		'active'                => true,
		'description'           => 'GENERATED by `wp lp acf:build` from blocks/*/fields.php — edits here are overwritten.',
		'show_in_rest'          => 0,
	);
}

/**
 * Assign deterministic keys and resolve sibling-name conditionals.
 *
 * Helpers return fields without keys so they can be reused across layouts; the
 * key is derived from the field's full path, which is unique by construction.
 *
 * @param array  $fields Fields, by reference.
 * @param string $path   Path prefix for key derivation.
 */
function lp_acf_assign_keys( array &$fields, string $path ): void {
	$sibling_keys = array();

	// First pass — every sibling needs a key before conditionals can resolve.
	foreach ( $fields as &$field ) {
		if ( ! is_array( $field ) || ! isset( $field['name'] ) ) {
			continue;
		}
		$field['key']                        = 'field_' . substr( md5( $path . '/' . $field['name'] ), 0, 16 );
		$sibling_keys[ $field['name'] ]      = $field['key'];
	}
	unset( $field );

	// Second pass — resolve references and recurse.
	foreach ( $fields as &$field ) {
		if ( ! is_array( $field ) || ! isset( $field['name'] ) ) {
			continue;
		}

		if ( ! empty( $field['lp_conditional'] ) ) {
			$field['conditional_logic'] = lp_resolve_conditional( $field['lp_conditional'], $sibling_keys, $path );
			unset( $field['lp_conditional'] );
		}

		$child_path = $path . '/' . $field['name'];

		if ( ! empty( $field['sub_fields'] ) && is_array( $field['sub_fields'] ) ) {
			lp_acf_assign_keys( $field['sub_fields'], $child_path );
		}

		if ( ! empty( $field['layouts'] ) && is_array( $field['layouts'] ) ) {
			$rekeyed = array();
			foreach ( $field['layouts'] as $layout ) {
				$layout['key'] = 'layout_' . substr( md5( $child_path . '/' . $layout['name'] ), 0, 16 );
				if ( ! empty( $layout['sub_fields'] ) ) {
					lp_acf_assign_keys( $layout['sub_fields'], $child_path . '/' . $layout['name'] );
				}
				$rekeyed[ $layout['key'] ] = $layout;
			}
			$field['layouts'] = $rekeyed;
		}
	}
	unset( $field );
}

/**
 * Turn sibling-name conditionals into ACF's key-based conditional_logic.
 *
 * @param array  $groups       Conditional groups referencing sibling names.
 * @param array  $sibling_keys name => key map.
 * @param string $path         Path, for error reporting.
 * @return array
 */
function lp_resolve_conditional( array $groups, array $sibling_keys, string $path ): array {
	$resolved = array();

	foreach ( $groups as $group ) {
		$rules = array();
		foreach ( (array) $group as $rule ) {
			$name = $rule['field'] ?? '';
			if ( ! isset( $sibling_keys[ $name ] ) ) {
				lp_build_warn( "conditional references unknown sibling '{$name}' at {$path}" );
				continue;
			}
			$rule['field'] = $sibling_keys[ $name ];
			$rules[]       = $rule;
		}
		if ( $rules ) {
			$resolved[] = $rules;
		}
	}

	return $resolved;
}

/**
 * Collect build warnings so the CLI command can report them all at once.
 *
 * @param string|null $message Message to record, or null to read and reset.
 * @return array
 */
function lp_build_warn( ?string $message = null ): array {
	static $warnings = array();

	if ( null === $message ) {
		$out      = $warnings;
		$warnings = array();
		return $out;
	}

	$warnings[] = $message;
	return $warnings;
}

/**
 * Every field group this theme generates.
 *
 * @return array<int, array>
 */
function lp_all_field_groups(): array {
	$groups   = array( lp_build_sections_group() );
	$extra    = get_theme_file_path( 'app/setup/acf-groups.php' );

	if ( is_readable( $extra ) ) {
		$more = require $extra;
		if ( is_array( $more ) ) {
			$groups = array_merge( $groups, $more );
		}
	}

	foreach ( $groups as &$group ) {
		lp_acf_assign_keys( $group['fields'], $group['key'] );
	}
	unset( $group );

	return $groups;
}

/**
 * Assert the ACF UI stays consistent across every block.
 *
 * An editor must see the same labels, in the same order, in every block. This
 * is a drift check that runs on every build, not a one-off review.
 *
 * @param array $groups Generated groups.
 * @return array<int, string> Problems found.
 */
function lp_assert_field_consistency( array $groups ): array {
	$problems  = array();
	$tab_order = array( 'Content', 'Items', 'Actions', 'Settings' );
	$seen      = array();  // field name => array( label, type, layout ).
	$sources   = array();  // layout => source choices.

	/*
	 * The two fields lp_field_source() deliberately varies per block. Its
	 * signature takes a $label precisely so the editor reads "Sites" on
	 * TrainInPerson and "Session" on CTA, and its `multiple` option switches
	 * source_items between relationship and post_object — a one-session block
	 * must not offer a multi-picker. Checking those here would force every
	 * list-backed block to share one meaningless label. Everything ELSE the
	 * helper emits (source, source_limit, source_terms) is still compared, so
	 * the control itself cannot drift.
	 */
	$parameterised = array( 'source_items', 'source_manual' );

	$sections = null;
	foreach ( $groups as $group ) {
		if ( 'group_lp_page_sections' === $group['key'] ) {
			$sections = $group;
		}
	}

	if ( ! $sections ) {
		return array( 'no Page Sections group was generated' );
	}

	$layouts = $sections['fields'][0]['layouts'] ?? array();

	foreach ( $layouts as $layout ) {
		$name = $layout['name'];
		$tabs = array();

		foreach ( $layout['sub_fields'] ?? array() as $field ) {
			if ( 'tab' === ( $field['type'] ?? '' ) ) {
				$tabs[] = $field['label'];
				continue;
			}

			$fname = $field['name'] ?? '';
			$label = $field['label'] ?? '';
			$type  = $field['type'] ?? '';

			if ( in_array( $fname, $parameterised, true ) ) {
				continue;
			}

			// Shared vocabulary must mean the same thing everywhere.
			if ( isset( $seen[ $fname ] ) ) {
				if ( $seen[ $fname ]['label'] !== $label ) {
					$problems[] = sprintf(
						"field '%s' is labelled '%s' in %s but '%s' in %s",
						$fname,
						$seen[ $fname ]['label'],
						$seen[ $fname ]['layout'],
						$label,
						$name
					);
				}
				if ( $seen[ $fname ]['type'] !== $type ) {
					$problems[] = sprintf(
						"field '%s' is a %s in %s but a %s in %s",
						$fname,
						$seen[ $fname ]['type'],
						$seen[ $fname ]['layout'],
						$type,
						$name
					);
				}
			} else {
				$seen[ $fname ] = array(
					'label'  => $label,
					'type'   => $type,
					'layout' => $name,
				);
			}

			if ( 'source' === $fname ) {
				$sources[ $name ] = array_keys( $field['choices'] ?? array() );
			}
		}

		// Tabs must be a subsequence of the canonical order.
		$expected = array_values( array_intersect( $tab_order, $tabs ) );
		if ( $tabs !== $expected ) {
			$problems[] = sprintf(
				'%s tabs are [%s]; expected a subsequence of [%s]',
				$name,
				implode( ', ', $tabs ),
				implode( ', ', $tab_order )
			);
		}
	}

	// Every source control offers the same choices in the same order.
	$canonical = null;
	foreach ( $sources as $layout => $choices ) {
		if ( null === $canonical ) {
			$canonical = $choices;
			continue;
		}
		if ( $choices !== $canonical ) {
			$problems[] = sprintf(
				"%s source offers [%s]; every other block offers [%s]",
				$layout,
				implode( ', ', $choices ),
				implode( ', ', $canonical )
			);
		}
	}

	return $problems;
}

/**
 * Write generated field groups and lp_* CPT/taxonomy JSON to acf-json/.
 *
 * @return array{
 *   field_groups:int,
 *   post_types:int,
 *   taxonomies:int,
 *   preserved:int,
 *   problems:array,
 *   warnings:array
 * }
 */
function lp_acf_build(): array {
	$dir = get_theme_file_path( 'acf-json' );

	if ( ! is_dir( $dir ) ) {
		wp_mkdir_p( $dir );
	}

	$groups   = lp_all_field_groups();
	$problems = lp_assert_field_consistency( $groups );
	$written  = 0;

	foreach ( $groups as $group ) {
		$file = $dir . '/' . $group['key'] . '.json';
		$json = wp_json_encode( $group, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );

		if ( false !== file_put_contents( $file, $json . "\n" ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
			++$written;
		}
	}

	$cpt_result = lp_acf_write_cpt_taxonomy_json();

	foreach ( lp_acf_validate_manifest() as $missing ) {
		$problems[] = $missing;
	}

	$manifest = lp_acf_preserved_json_manifest();
	$preserved = count( $manifest['field_groups'] )
		+ count( $manifest['post_types'] )
		+ count( $manifest['taxonomies'] );

	return array(
		'field_groups' => $written,
		'post_types'   => $cpt_result['post_types'],
		'taxonomies'   => $cpt_result['taxonomies'],
		'preserved'    => $preserved,
		'problems'     => $problems,
		'warnings'     => lp_build_warn(),
	);
}

if ( defined( 'WP_CLI' ) && WP_CLI ) {
	/**
	 * LondonParkour theme commands.
	 */
	class LP_CLI_Command {

		/**
		 * Compose ACF definitions from PHP into acf-json/ and optionally sync to DB.
		 *
		 * ## OPTIONS
		 *
		 * [--check]
		 * : Only run the consistency assertion; write nothing.
		 *
		 * [--sync]
		 * : After writing JSON, run `wp acf json sync` so items appear in wp-admin.
		 *
		 * @param array $args Positional args.
		 * @param array $assoc_args Flags.
		 */
		public function __invoke( $args, $assoc_args ) {
			$check_only = isset( $assoc_args['check'] );
			$do_sync    = isset( $assoc_args['sync'] );

			if ( $check_only ) {
				$groups   = lp_all_field_groups();
				$problems = lp_assert_field_consistency( $groups );
				$problems = array_merge( $problems, lp_acf_validate_manifest() );
				$result   = array(
					'field_groups' => 0,
					'post_types'   => 0,
					'taxonomies'   => 0,
					'preserved'    => 0,
					'problems'     => $problems,
					'warnings'     => lp_build_warn(),
				);
			} else {
				$result = lp_acf_build();
			}

			foreach ( $result['warnings'] as $warning ) {
				WP_CLI::warning( $warning );
			}

			$layouts = count( lp_collect_block_layouts() );

			if ( $result['problems'] ) {
				foreach ( $result['problems'] as $problem ) {
					WP_CLI::log( '  ✗ ' . $problem );
				}
				WP_CLI::error(
					sprintf( 'ACF build: %d problem(s) across %d block(s).', count( $result['problems'] ), $layouts )
				);
			}

			if ( $check_only ) {
				WP_CLI::success( sprintf( 'ACF UI consistent across %d block(s).', $layouts ) );
				return;
			}

			$inventory = lp_acf_json_inventory();

			WP_CLI::log(
				sprintf(
					'JSON: %d field group(s), %d post type(s), %d taxonom%s (%d v7-preserved)',
					$inventory['field_groups'],
					$inventory['post_types'],
					$inventory['taxonomies'],
					1 === $inventory['taxonomies'] ? 'y' : 'ies',
					$result['preserved']
				)
			);

			if ( $do_sync ) {
				WP_CLI::log( 'Syncing local JSON → database…' );
				$sync = lp_acf_sync_json_to_database();
				if ( $sync['output'] ) {
					WP_CLI::log( trim( $sync['output'] ) );
				}

				$counts = lp_acf_admin_counts();
				WP_CLI::log(
					sprintf(
						'Database: %d/%d field groups, %d/%d post types, %d/%d taxonomies synced',
						$counts['field_groups_db'],
						$counts['field_groups'],
						$counts['post_types_db'],
						$counts['post_types'],
						$counts['taxonomies_db'],
						$counts['taxonomies']
					)
				);
			}

			WP_CLI::success(
				sprintf(
					'Wrote %d field group(s), %d post type(s), %d taxonom%s from %d block layout(s).',
					$result['field_groups'],
					$result['post_types'],
					$result['taxonomies'],
					1 === $result['taxonomies'] ? 'y' : 'ies',
					$layouts
				)
			);
		}
	}

	WP_CLI::add_command( 'lp acf:build', 'LP_CLI_Command' );

	/**
	 * Render one block to stdout without writing any content.
	 *
	 * The verification tool for the port: it proves a block's markup against
	 * the Storybook without needing a page, a post, or seeded data.
	 *
	 *   wp lp render train_in_person
	 *   wp lp render train_in_person --args='{"eyebrow":"HELLO"}'
	 *   wp lp render train_in_person --args-file=blocks/train-in-person/example.json
	 */
	WP_CLI::add_command(
		'lp render',
		function ( $args, $assoc_args ) {
			$layout = $args[0] ?? '';

			if ( '' === $layout ) {
				WP_CLI::error( 'Usage: wp lp render <layout> [--args=<json>] [--args-file=<path>]' );
			}

			$data = array();

			if ( ! empty( $assoc_args['args-file'] ) ) {
				$path = $assoc_args['args-file'];
				if ( ! is_readable( $path ) ) {
					$path = get_theme_file_path( ltrim( $assoc_args['args-file'], '/' ) );
				}
				if ( ! is_readable( $path ) ) {
					WP_CLI::error( 'Cannot read ' . $assoc_args['args-file'] );
				}
				$data = json_decode( (string) file_get_contents( $path ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			} elseif ( ! empty( $assoc_args['args'] ) ) {
				$data = json_decode( (string) $assoc_args['args'], true );
			}

			if ( ! is_array( $data ) ) {
				WP_CLI::error( 'args must be a JSON object: ' . json_last_error_msg() );
			}

			// Fall back to the block's own example fixture when none is given.
			if ( ! $data ) {
				$slug    = str_replace( '_', '-', $layout );
				$example = get_theme_file_path( "blocks/{$slug}/example.json" );
				if ( is_readable( $example ) ) {
					$data = json_decode( (string) file_get_contents( $example ), true ) ?: array(); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
				}
			}

			lp_render_block( $layout, $data );
		}
	);

	/**
	 * Render one partial to stdout. The `lp render` of Phase 3.
	 *
	 * Components are not blocks — they have no ACF layout and so no way to
	 * reach `lp render`. This proves their markup against the Storybook
	 * without a page, a post, or seeded data.
	 *
	 *   wp lp part elements/button
	 *   wp lp part components/byline --args='{"size":"sm","surface":"accent"}'
	 *   wp lp part components/byline --args-file=parts/components/byline.example.json
	 */
	WP_CLI::add_command(
		'lp part',
		function ( $args, $assoc_args ) {
			$slug = $args[0] ?? '';

			if ( '' === $slug ) {
				WP_CLI::error( 'Usage: wp lp part <slug> [--args=<json>] [--args-file=<path>]' );
			}

			if ( ! is_readable( get_theme_file_path( "parts/{$slug}.php" ) ) ) {
				WP_CLI::error( "No such partial: parts/{$slug}.php" );
			}

			$data = array();

			if ( ! empty( $assoc_args['args-file'] ) ) {
				$path = $assoc_args['args-file'];
				if ( ! is_readable( $path ) ) {
					$path = get_theme_file_path( ltrim( $assoc_args['args-file'], '/' ) );
				}
				if ( ! is_readable( $path ) ) {
					WP_CLI::error( 'Cannot read ' . $assoc_args['args-file'] );
				}
				$data = json_decode( (string) file_get_contents( $path ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			} elseif ( ! empty( $assoc_args['args'] ) ) {
				$data = json_decode( (string) $assoc_args['args'], true );
			}

			if ( ! is_array( $data ) ) {
				WP_CLI::error( 'args must be a JSON object: ' . json_last_error_msg() );
			}

			lp_part( $slug, $data );
			echo "\n";
		}
	);
}
