<?php
/**
 * Field groups that are not block layouts — the CPTs and the options page.
 *
 * Returned to lp_all_field_groups() in acf-build.php, which assigns keys and
 * writes the JSON. Field shapes are taken from the Storybook components that
 * consume them, so a record carries exactly what the blocks project from.
 *
 * @package londonparkour_v8
 */

defined( 'ABSPATH' ) || exit;

/**
 * Location rule helper.
 *
 * @param string $param    Rule param, e.g. 'post_type'.
 * @param string $value    Rule value.
 * @return array
 */
$lp_where = static function ( string $param, string $value ): array {
	return array( array( array( 'param' => $param, 'operator' => '==', 'value' => $value ) ) );
};

return array(

	/*
	 * Class theme fields live in preserved acf-json/group_lp_class.json on
	 * clasbpro_class — not generated here (see acf-manifest.php).
	 */

	/* ── Coaches ─────────────────────────────────────────────────────────
	 * Feeds the Coaches block: one lead coach (portrait + quote) and a roster
	 * of thumbnails. Name is the post title; portrait is the featured image.
	 */
	array(
		'key'             => 'group_lp_coach',
		'title'           => __( 'Coach', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_coach' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'role',
				'label'        => __( 'Role', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "HEAD COACH / 11 YRS"', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'specialty',
				'label'        => __( 'Specialty', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "Precision & balance"', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'location',
				'label'         => __( 'Location', 'londonparkour_v8' ),
				'type'          => 'post_object',
				'post_type'     => array( 'lp_location' ),
				'return_format' => 'id',
				'allow_null'    => 1,
				'instructions'  => __( 'Class site only — training spots do not appear here.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'quote',
				'label'        => __( 'Quote', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'Shown only when this coach leads the Coaches block.', 'londonparkour_v8' ),
			),
			/*
			 * Mirrors `is_flagship` on Location, and for the same reason: the
			 * Coaches block features one coach separately and then lists the
			 * roster, so the roster query has to know who is already on show.
			 * Without it the lead appears twice. See PORT-FINDINGS §13.
			 */
			array(
				'name'          => 'is_lead',
				'label'         => __( 'Lead coach', 'londonparkour_v8' ),
				'type'          => 'true_false',
				'ui'            => 1,
				'default_value' => 0,
				'instructions'  => __( 'Featured above the roster, and left out of it.', 'londonparkour_v8' ),
			),
			/*
			 * ClassDetail's Meeting Point band closes with Byline `size: 'lg'`
			 * carrying a `bio`. `quote` beside it is a different thing — a
			 * pull-quote the Coaches block prints in the coach's own voice —
			 * so the two do not collapse into one field.
			 */
			array(
				'name'         => 'bio',
				'label'        => __( 'Bio', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'One or two sentences, shown beside the coach on a class page.', 'londonparkour_v8' ),
			),
		),
	),

	/* ── Locations ───────────────────────────────────────────────────────
	 * Feeds the Locations block (flagship card + site list) and TrainInPerson
	 * (kicker/title/detail). Same record, two projections.
	 */
	array(
		'key'             => 'group_lp_location',
		'title'           => __( 'Location', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_location' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'          => 'location_kind',
				'label'         => __( 'Place kind', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'choices'       => array(
					'site' => __( 'Site', 'londonparkour_v8' ),
					'spot' => __( 'Spot', 'londonparkour_v8' ),
				),
				'default_value' => 'site',
				'instructions'  => __( 'Sites are class locations (map + meeting points). Spots are training points shown on the map only — title, coordinates and Street View are enough.', 'londonparkour_v8' ),
			),
			lp_field_eyebrow(
				array(
					'name'           => 'tag',
					'label'          => __( 'Tag', 'londonparkour_v8' ),
					'instructions'   => __( 'e.g. "INDOOR SITE"', 'londonparkour_v8' ),
					'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
				)
			),
			array(
				'name'           => 'meta',
				'label'          => __( 'Meta', 'londonparkour_v8' ),
				'type'           => 'text',
				'instructions'   => __( 'e.g. "SW8 1SR · 4 MIN FROM VAUXHALL · OPEN 07:00–22:00"', 'londonparkour_v8' ),
				'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
			),
			array(
				'name'           => 'type',
				'label'          => __( 'Type', 'londonparkour_v8' ),
				'type'           => 'button_group',
				'choices'        => array(
					'INDOOR'  => __( 'Indoor', 'londonparkour_v8' ),
					'OUTDOOR' => __( 'Outdoor', 'londonparkour_v8' ),
				),
				'default_value'  => 'INDOOR',
				'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
			),
			/*
			 * Plain text, not ACF's `google_map` field: that type needs a
			 * Google Maps JS API key registered on `acf/init`, which this
			 * project has never configured and which would put an external
			 * service and a billing account behind the admin screen. Two text
			 * fields need neither. ClassesMap feeds them to Leaflet.
			 */
			array(
				'name'  => 'latitude',
				'label' => __( 'Latitude', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'  => 'longitude',
				'label' => __( 'Longitude', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'         => 'streetview',
				'label'        => __( 'Street View URL', 'londonparkour_v8' ),
				'type'         => 'url',
				'instructions' => __( 'Optional for sites; recommended for spots. Paste a Google Street View (or other) URL. If empty, the map falls back to a Maps link at the coordinates above.', 'londonparkour_v8' ),
			),
			/*
			 * Site-only SitePanel fields. Spots skip meeting points entirely.
			 */
			array(
				'name'           => 'meeting_point',
				'label'          => __( 'Meeting point', 'londonparkour_v8' ),
				'type'           => 'textarea',
				'rows'           => 2,
				'new_lines'      => '',
				'instructions'   => __( 'Where to stand, in one sentence. e.g. "Outside Tube station exit 2, next to metal pillars and open area."', 'londonparkour_v8' ),
				'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
			),
			array(
				'name'           => 'transport_rail',
				'label'          => __( 'Transport — rail', 'londonparkour_v8' ),
				'type'           => 'text',
				'instructions'   => __( 'e.g. "Victoria Underground Line · Vauxhall (South Western Railway)"', 'londonparkour_v8' ),
				'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
			),
			array(
				'name'           => 'transport_bus',
				'label'          => __( 'Transport — bus', 'londonparkour_v8' ),
				'type'           => 'text',
				'instructions'   => __( 'e.g. "Buses — 2 · 36 · 87 · 88 · 156 · 185 · 196 · 344 · 436"', 'londonparkour_v8' ),
				'lp_conditional' => array( array( array( 'field' => 'location_kind', 'operator' => '==', 'value' => 'site' ) ) ),
			),
		),
	),

	/*
	 * Tutorial fields live in preserved v7 JSON — Tutorial Fields
	 * (`group_6195097cc6251`) and Tutorial Sidebar (`group_6721ddb5b7f7a`) —
	 * not generated here (see acf-manifest.php).
	 */

	/* ── Testimonials ────────────────────────────────────────────────────
	 * Google review mirror. Title is the author; content is the full review
	 * text. `quote` is editor-owned once set — import fills it only when empty.
	 */
	array(
		'key'             => 'group_lp_testimonial',
		'title'           => __( 'Testimonial', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'lp_testimonial' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'quote',
				'label'        => __( 'Quote', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'Pull-quote. Import fills this only when empty. Re-import will not overwrite or clear it.', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'rating',
				'label'         => __( 'Rating', 'londonparkour_v8' ),
				'type'          => 'number',
				'min'           => 1,
				'max'           => 5,
				'step'          => 1,
				'instructions'  => __( 'Google star rating, 1–5.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'reviewed_at',
				'label'        => __( 'Reviewed at', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'Google’s date string as-is, e.g. "18 weeks ago" or "20 May 2023".', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'rating_only',
				'label'         => __( 'Rating only', 'londonparkour_v8' ),
				'type'          => 'true_false',
				'ui'            => 1,
				'default_value' => 0,
				'instructions'  => __( 'No written review — stars only.', 'londonparkour_v8' ),
			),
			lp_tab( __( 'Source', 'londonparkour_v8' ) ),
			array(
				'name'         => 'review_id',
				'label'        => __( 'Google review ID', 'londonparkour_v8' ),
				'type'         => 'text',
				'readonly'     => 1,
				'instructions' => __( 'Identity key. Do not edit — import matches on this.', 'londonparkour_v8' ),
			),
			array(
				'name'  => 'author_id',
				'label' => __( 'Author ID', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'  => 'author_profile_url',
				'label' => __( 'Author profile URL', 'londonparkour_v8' ),
				'type'  => 'url',
			),
			array(
				'name'  => 'author_photo_url',
				'label' => __( 'Author photo URL', 'londonparkour_v8' ),
				'type'  => 'url',
			),
			array(
				'name'  => 'business_name',
				'label' => __( 'Business name', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'  => 'location_label',
				'label' => __( 'Location', 'londonparkour_v8' ),
				'type'  => 'text',
			),
			array(
				'name'      => 'owner_reply',
				'label'     => __( 'Owner reply', 'londonparkour_v8' ),
				'type'      => 'textarea',
				'rows'      => 3,
				'new_lines' => '',
			),
			array(
				'name'  => 'owner_reply_date',
				'label' => __( 'Owner reply date', 'londonparkour_v8' ),
				'type'  => 'text',
			),
		),
	),

	/* ── Series (lp_series terms) ────────────────────────────────────────
	 * Feeds the Homepage Tutorials block (featured + shelf) and B5
	 * TutorialsSeries. Title is the term name — never duplicated here.
	 */
	array(
		'key'             => 'group_lp_series',
		'title'           => __( 'Series', 'londonparkour_v8' ),
		'location'        => $lp_where( 'taxonomy', 'lp_series' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'tag',
				'label'        => __( 'Tag', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "START HERE" / "POPULAR"', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'series_label',
				'label'        => __( 'Series label', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'Level only ("BEGINNER") or the full line ("SERIES 01 · BEGINNER"). Number falls back to list order.', 'londonparkour_v8' ),
			),
			array(
				'name'  => 'logline',
				'label' => __( 'Logline', 'londonparkour_v8' ),
				'type'  => 'textarea',
				'rows'  => 3,
			),
			array(
				'name'         => 'tags',
				'label'        => __( 'Tags', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'Comma-separated uppercase labels, e.g. "VAULTING, FUNDAMENTALS".', 'londonparkour_v8' ),
			),
			lp_field_media( array( 'name' => 'poster' ) ),
			array(
				'name'         => 'episode_count',
				'label'        => __( 'Episode count', 'londonparkour_v8' ),
				'type'         => 'number',
				'min'          => 0,
				'instructions' => __( 'Rendered as "8 EPISODES" / "6 EPS" by the block.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'duration',
				'label'        => __( 'Duration', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'Featured meta only, e.g. "34 MIN".', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'coach_label',
				'label'        => __( 'Coach label', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'Featured meta only, e.g. "LEON LAWRENCE".', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'cta_label',
				'label'         => __( 'CTA label', 'londonparkour_v8' ),
				'type'          => 'text',
				'default_value' => 'WATCH SERIES',
			),
			array(
				'name'          => 'layout',
				'label'         => __( 'Lesson layout', 'londonparkour_v8' ),
				'type'          => 'select',
				'choices'       => array(
					'categories' => __( 'Categories (horizontal shelves)', 'londonparkour_v8' ),
					'grid'       => __( 'Grid (full cards)', 'londonparkour_v8' ),
				),
				'default_value' => 'categories',
			),
		),
	),

	/* ── Legal ───────────────────────────────────────────────────────────
	 * Feeds templates/legal.php. Doc facts, doc actions and the ten clauses
	 * are structured because the body's "ON THIS PAGE" index rail is keyed to
	 * clause numbers and jumps to per-clause ids — the Storybook source itself
	 * says this list is prose furniture, not a ListRow, but it still has to be
	 * data, not the_content(). Copy defaults (the ten clauses' own text, the
	 * doc facts, the doc actions, the pager labels) live in templates/legal.php
	 * as $args fallbacks, taken verbatim from Legal.js's own DOC_FACTS /
	 * DOC_ACTIONS / CLAUSES constants — never here.
	 *
	 * `prev` / `next` are bare ACF Link fields, not the lp_field_action()
	 * group: the source's own pager points at a Privacy and a Cookie policy
	 * that exist in neither the design nor this repo, so an editor sets the
	 * link only once real pages exist. Until then the template falls back to
	 * the source's labels with no href, exactly as the port brief requires.
	 */
	array(
		'key'             => 'group_lp_legal',
		'title'           => __( 'Legal', 'londonparkour_v8' ),
		'location'        => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'templates/legal.php',
				),
			),
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'support',
				),
			),
		),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Items', 'londonparkour_v8' ) ),
			array(
				'name'         => 'doc_facts',
				'label'        => __( 'Doc facts', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'table',
				'button_label' => __( 'Add fact', 'londonparkour_v8' ),
				'instructions' => __( 'e.g. "EFFECTIVE" / "1 April 2026". Shown left of the doc-meta rule.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'label',
						'label' => __( 'Label', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'  => 'value',
						'label' => __( 'Value', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'         => 'clauses',
				'label'        => __( 'Clauses', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add clause', 'londonparkour_v8' ),
				'instructions' => __( 'Each becomes a numbered heading in the body and a row in the "On this page" index.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'         => 'number',
						'label'        => __( 'Number', 'londonparkour_v8' ),
						'type'         => 'text',
						'instructions' => __( 'e.g. "01"', 'londonparkour_v8' ),
					),
					array(
						'name'  => 'title',
						'label' => __( 'Title', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'         => 'paragraphs',
						'label'        => __( 'Paragraphs', 'londonparkour_v8' ),
						'type'         => 'repeater',
						'layout'       => 'table',
						'button_label' => __( 'Add paragraph', 'londonparkour_v8' ),
						'sub_fields'   => array(
							array(
								'name'      => 'text',
								'label'     => __( 'Paragraph', 'londonparkour_v8' ),
								'type'      => 'textarea',
								'rows'      => 3,
								'new_lines' => '',
							),
						),
					),
				),
			),

			lp_tab( __( 'Actions', 'londonparkour_v8' ) ),
			array(
				'name'         => 'doc_actions',
				'label'        => __( 'Doc actions', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'table',
				'button_label' => __( 'Add action', 'londonparkour_v8' ),
				'instructions' => __( 'e.g. "DOWNLOAD PDF ↓". Right of the doc-meta rule; not yet linked to a real destination.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'label',
						'label' => __( 'Label', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'          => 'prev',
				'label'         => __( 'Previous page', 'londonparkour_v8' ),
				'type'          => 'link',
				'return_format' => 'array',
				'instructions'  => __( 'The link text is the pager label. Leave empty to show the default label with no link.', 'londonparkour_v8' ),
			),
			array(
				'name'          => 'next',
				'label'         => __( 'Next page', 'londonparkour_v8' ),
				'type'          => 'link',
				'return_format' => 'array',
				'instructions'  => __( 'The link text is the pager label. Leave empty to show the default label with no link.', 'londonparkour_v8' ),
			),
		),
	),

	/* ── Private 1:1 ─────────────────────────────────────────────────────
	 * Feeds templates/private-coaching.php. Copy stays in the template
	 * (Storybook PrivateCoaching.js defaults). The featured image is the
	 * opening portrait. appointment_class is the one value WordPress has
	 * no native home for — it wires BOOK 1:1 to the shared overlay.
	 */
	array(
		'key'             => 'group_lp_private_coaching',
		'title'           => __( 'Private 1:1', 'londonparkour_v8' ),
		'location'        => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => 'templates/private-coaching.php',
				),
			),
		),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Actions', 'londonparkour_v8' ) ),
			array(
				'name'          => 'appointment_class',
				'label'         => __( 'Appointment class', 'londonparkour_v8' ),
				'type'          => 'post_object',
				'post_type'     => array( 'clasbpro_class' ),
				'return_format' => 'id',
				'allow_null'    => 1,
				'ui'            => 1,
				'instructions'  => __( 'When set, BOOK 1:1 opens the shared booking overlay for this clasbpro appointment class.', 'londonparkour_v8' ),
			),
		),
	),

	/* ── Support (wiki / legal docs) ─────────────────────────────────────
	 * Column in the Docs Index, and whether /docs/{slug} uses wiki chrome
	 * or the Legal (Terms) template. Only Terms of service is Legal; every
	 * other support post is a wiki article. Unset values read as Classes + Wiki.
	 */
	array(
		'key'             => 'group_lp_support',
		'title'           => __( 'Docs', 'londonparkour_v8' ),
		'location'        => $lp_where( 'post_type', 'support' ),
		'menu_order'      => 0,
		'position'        => 'side',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			array(
				'name'          => 'docs_index_group',
				'label'         => __( 'Index column', 'londonparkour_v8' ),
				'type'          => 'select',
				'choices'       => array(
					'classes' => __( 'Classes', 'londonparkour_v8' ),
					'company' => __( 'Company', 'londonparkour_v8' ),
					'website' => __( 'Website', 'londonparkour_v8' ),
				),
				'default_value' => 'classes',
				'allow_null'    => 0,
			),
			array(
				'name'          => 'docs_template',
				'label'         => __( 'Template', 'londonparkour_v8' ),
				'type'          => 'select',
				'choices'       => array(
					'wiki'  => __( 'Wiki', 'londonparkour_v8' ),
					'legal' => __( 'Legal', 'londonparkour_v8' ),
					'faq'   => __( 'FAQ', 'londonparkour_v8' ),
				),
				'default_value' => 'wiki',
				'allow_null'    => 0,
			),
		),
	),

	/* ── Blog (CPT `blog`, plus native `post` if any remain) ─────────────
	 * Feeds home.php (BlogIndex) and single.php / single-blog.php
	 * (BlogDetail). The v7 import writes the `blog` CPT; this group is
	 * attached to both types so a structured article can still be authored
	 * in ACF. Imported posts have empty repeaters — those templates parse
	 * markdown `post_content` instead of falling back to Imperial copy.
	 */
	array(
		'key'             => 'group_lp_post',
		'title'           => __( 'Blog', 'londonparkour_v8' ),
		'location'        => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'blog',
				),
			),
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
		),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Content', 'londonparkour_v8' ) ),
			array(
				'name'         => 'read_time',
				'label'        => __( 'Read time', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "3 MIN READ". Shown on the blog index card and the article meta line.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'standfirst',
				'label'        => __( 'Standfirst', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 2,
				'new_lines'    => '',
				'instructions' => __( 'The intro line under the article title. Separate from the excerpt, which is what the blog index card shows.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'author_role',
				'label'        => __( 'Author role', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "HEAD COACH". Shown next to the author name.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'caption_location',
				'label'        => __( 'Photo location', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "IMPERIAL COLLEGE LONDON · SOUTH KENSINGTON". Left side of the caption band under the hero photo.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'caption_credit',
				'label'        => __( 'Photo credit', 'londonparkour_v8' ),
				'type'         => 'text',
				'instructions' => __( 'e.g. "PHOTO: LONDONPARKOUR". Right side of the caption band.', 'londonparkour_v8' ),
			),
			array(
				'name'         => 'body_intro',
				'label'        => __( 'Body intro', 'londonparkour_v8' ),
				'type'         => 'textarea',
				'rows'         => 3,
				'new_lines'    => '',
				'instructions' => __( 'The first paragraph of the article body, before the first heading.', 'londonparkour_v8' ),
			),

			lp_tab( __( 'Items', 'londonparkour_v8' ) ),
			array(
				'name'         => 'body_sections',
				'label'        => __( 'Body sections', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add section', 'londonparkour_v8' ),
				'instructions' => __( 'Sections before the pull-quote. Each becomes an H3 in the article and a row in the "In this article" index — its anchor id is derived from the heading.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'heading',
						'label' => __( 'Heading', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'      => 'body',
						'label'     => __( 'Body', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 4,
						'new_lines' => '',
					),
				),
			),
			array(
				'name'         => 'pull_quote',
				'label'        => __( 'Pull quote', 'londonparkour_v8' ),
				'type'         => 'group',
				'layout'       => 'block',
				'instructions' => __( 'Sits between the two section groups below.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'      => 'quote',
						'label'     => __( 'Quote', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 2,
						'new_lines' => '',
					),
					array(
						'name'  => 'attribution',
						'label' => __( 'Attribution', 'londonparkour_v8' ),
						'type'  => 'text',
					),
				),
			),
			array(
				'name'         => 'body_sections_after_quote',
				'label'        => __( 'Body sections (after quote)', 'londonparkour_v8' ),
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add section', 'londonparkour_v8' ),
				'instructions' => __( 'Sections after the pull-quote. Same shape as the sections above.', 'londonparkour_v8' ),
				'sub_fields'   => array(
					array(
						'name'  => 'heading',
						'label' => __( 'Heading', 'londonparkour_v8' ),
						'type'  => 'text',
					),
					array(
						'name'      => 'body',
						'label'     => __( 'Body', 'londonparkour_v8' ),
						'type'      => 'textarea',
						'rows'      => 4,
						'new_lines' => '',
					),
				),
			),
		),
	),

	/* ── Site settings ───────────────────────────────────────────────────
	 * The theme is two axes composed into one data-theme value, exactly as the
	 * Storybook toolbar composes it. Read by lp_theme_name().
	 */
	array(
		'key'             => 'group_lp_site_settings',
		'title'           => __( 'Site Settings', 'londonparkour_v8' ),
		'location'        => $lp_where( 'options_page', 'lp-site-settings' ),
		'menu_order'      => 0,
		'position'        => 'normal',
		'style'           => 'default',
		'label_placement' => 'top',
		'active'          => true,
		'description'     => 'GENERATED by `wp lp acf:build` — edits here are overwritten.',
		'fields'          => array(
			lp_tab( __( 'Settings', 'londonparkour_v8' ) ),
			array(
				'name'          => 'theme_ground',
				'label'         => __( 'Ground', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'instructions'  => __( 'The page background family.', 'londonparkour_v8' ),
				'choices'       => array(
					'light' => __( 'Light', 'londonparkour_v8' ),
					'dark'  => __( 'Dark', 'londonparkour_v8' ),
				),
				'default_value' => 'light',
			),
			array(
				'name'          => 'theme_signal',
				'label'         => __( 'Signal', 'londonparkour_v8' ),
				'type'          => 'button_group',
				'instructions'  => __( 'Yellow keeps Marquee/CTA/Private Coaching yellow. Light ground makes Pricing white and Clients/Locations the accent band.', 'londonparkour_v8' ),
				'choices'       => array(
					'yellow' => __( 'Yellow', 'londonparkour_v8' ),
					'green'  => __( 'Green', 'londonparkour_v8' ),
				),
				'default_value' => 'yellow',
			),
			array(
				'name'         => 'contact_email',
				'label'        => __( 'Contact email', 'londonparkour_v8' ),
				'type'         => 'email',
				'instructions' => __( 'Enquiry form recipient. Falls back to the WordPress admin email when empty.', 'londonparkour_v8' ),
			),
		),
	),
);
