<?php
/**
 * single-lp_tutorial.php — TutorialDetail.
 *
 * Ported from src/stories/Pages/TutorialDetail/TutorialDetail.js (`Fyf9i`).
 * Read that file's docblock before touching this one.
 *
 * Section order: breadcrumb → masthead → view rail → filter grid →
 * "01 Now Playing" → "02 The Series" → "03 Video Details" →
 * "04 Demonstrations" (when seeded) → Train In Person → onward.
 * Nav/footer are get_header()/get_footer(), outside the one <main>.
 *
 * ── Native / ACF data ───────────────────────────────────────────────────
 * Title, excerpt, featured image are native. `duration`, `video_url`,
 * `coaches`, `body`, `key_takeaways`, `closing_*` are optional post meta.
 * Demonstrations are two closest clips from the 2020 Demonstration Library
 * (same move, then family, then title). Series board rows are sibling
 * `lp_tutorial` posts in the same `lp_series` term. Filter grid posts to
 * the tutorials archive (same GET contract as archive-lp_tutorial.php).
 *
 * ── Gaps ────────────────────────────────────────────────────────────────
 * Resources with `href="#"` in the source are omitted as interactive links
 * (Port Brief: no dead anchors). Watch-progress tones (WATCHED / NOW PLAYING
 * fill) are derived only for the current post as NOW PLAYING; others are
 * WATCH or NEW — no per-user progress store.
 * Player chrome (scrub position, quality chip) uses duration + defaults;
 * there is no live player JS in this port.
 *
 * @package londonparkour_v8
 */

defined( 'ABSPATH' ) || exit;

while ( have_posts() ) :
	the_post();

	$lp_post_id   = get_the_ID();
	$lp_title     = get_the_title();
	$lp_excerpt   = get_the_excerpt();
	$lp_thumb_id  = get_post_thumbnail_id() ?: 0;
	$lp_video_id   = lp_tutorial_youtube_id( (int) $lp_post_id );
	$lp_video_dlg  = 'tutorial-video-' . (int) $lp_post_id;
	$lp_clock      = lp_format_runtime_clock( lp_tutorial_runtime_seconds( (int) $lp_post_id ) );
	$lp_duration   = $lp_clock;
	$lp_coaches    = function_exists( 'get_field' ) ? get_field( 'coaches' ) : array();
	$lp_coach_ids  = array_filter( array_map( 'intval', (array) $lp_coaches ) );

	$lp_raw_content   = trim( wp_strip_all_tags( (string) get_post_field( 'post_content', $lp_post_id ) ) );
	$lp_has_copy      = '' !== $lp_raw_content && 'description' !== strtolower( $lp_raw_content );

	$lp_body       = function_exists( 'get_field' ) ? get_field( 'body' ) : array();
	$lp_takeaways  = function_exists( 'get_field' ) ? get_field( 'key_takeaways' ) : array();
	$lp_closing    = function_exists( 'get_field' ) ? (string) get_field( 'closing_text' ) : '';
	$lp_ai_note    = function_exists( 'get_field' ) ? (string) get_field( 'closing_ai_note' ) : '';
	$lp_summary    = function_exists( 'get_field' ) ? trim( (string) get_field( 'video_transcript_chatgpt' ) ) : '';
	$lp_body       = is_array( $lp_body ) ? $lp_body : array();
	$lp_takeaways  = is_array( $lp_takeaways ) ? $lp_takeaways : array();
	$lp_parsed     = lp_tutorial_parse_chatgpt_summary( $lp_summary );
	$lp_summary_paras = $lp_parsed['paragraphs'];
	if ( $lp_parsed['takeaways'] ) {
		$lp_takeaways = $lp_parsed['takeaways'];
	}
	if ( $lp_summary_paras && '' === $lp_ai_note ) {
		$lp_ai_note = 'Note: this summary is generated by AI from the video transcript and may not always be accurate.';
	}

	$lp_series_terms = get_the_terms( $lp_post_id, 'lp_series' );
	$lp_series_term  = ( is_array( $lp_series_terms ) && $lp_series_terms ) ? $lp_series_terms[0] : null;

	$lp_archive_url = (string) get_post_type_archive_link( 'lp_tutorial' );
	$lp_series_url  = $lp_archive_url;
	if ( $lp_series_term ) {
		$lp_link = get_term_link( $lp_series_term );
		if ( ! is_wp_error( $lp_link ) ) {
			$lp_series_url = (string) $lp_link;
		}
	}

	list( $lp_parent_term, $lp_child_term ) = lp_tutorial_category_pair( $lp_post_id );
	$lp_category_name    = $lp_parent_term instanceof WP_Term ? $lp_parent_term->name : '';
	$lp_subcategory_name = $lp_child_term instanceof WP_Term ? $lp_child_term->name : '';
	$lp_kinds_default    = lp_tutorial_kind_defaults();
	$lp_category_url     = $lp_parent_term instanceof WP_Term
		? lp_tutorials_category_filter_url( $lp_parent_term->slug, $lp_kinds_default )
		: $lp_archive_url;
	$lp_subcategory_url  = $lp_child_term instanceof WP_Term
		? lp_tutorials_category_filter_url( $lp_child_term->slug, $lp_kinds_default )
		: '';

	$lp_listing_term = $lp_child_term instanceof WP_Term ? $lp_child_term : $lp_parent_term;
	$lp_siblings     = array();
	if ( $lp_listing_term instanceof WP_Term ) {
		$lp_siblings = lp_tutorials_in_category(
			(int) $lp_listing_term->term_id,
			300,
			$lp_series_term ? (int) $lp_series_term->term_id : 0
		);
	} elseif ( $lp_series_term ) {
		$lp_siblings = lp_tutorials_in_series( (int) $lp_series_term->term_id );
	}
	if ( ! $lp_siblings ) {
		$lp_siblings = array( get_post( $lp_post_id ) );
	}

	$lp_order_label  = lp_tutorial_order_label( $lp_post_id );
	$lp_lesson_index = 1;
	$lp_lesson_total = count( $lp_siblings );
	$lp_next_post    = null;
	foreach ( $lp_siblings as $lp_i => $lp_sib ) {
		if ( (int) $lp_sib->ID === (int) $lp_post_id ) {
			$lp_lesson_index = $lp_i + 1;
			$lp_next_post    = $lp_siblings[ $lp_i + 1 ] ?? null;
			break;
		}
	}
	if ( '' === $lp_order_label ) {
		$lp_order_label = sprintf( '%02d', $lp_lesson_index );
	}

	$lp_move_name        = '' !== $lp_subcategory_name ? $lp_subcategory_name : $lp_category_name;
	$lp_demo_posts       = lp_tutorial_related_demonstrations( (int) $lp_post_id, 2 );
	$lp_demos            = array();
	foreach ( $lp_demo_posts as $lp_demo_i => $lp_demo_post ) {
		$lp_demo_clock = lp_format_runtime_clock( lp_tutorial_runtime_seconds( (int) $lp_demo_post->ID ) );
		$lp_demo_n     = sprintf( '%02d', $lp_demo_i + 1 );
		$lp_demo_kick  = '' !== $lp_move_name
			? sprintf( 'DEMO %s · %s', $lp_demo_n, strtoupper( $lp_move_name ) )
			: sprintf( 'DEMO %s', $lp_demo_n );
		$lp_demos[]    = array(
			'image_id'   => (int) get_post_thumbnail_id( $lp_demo_post ),
			'kicker'     => $lp_demo_kick,
			'title'      => get_the_title( $lp_demo_post ),
			'meta'       => $lp_demo_clock,
			'foot_label' => '' !== $lp_demo_clock ? 'DEMONSTRATION · ' . $lp_demo_clock : 'DEMONSTRATION',
			'note'       => get_the_excerpt( $lp_demo_post ),
			'href'       => (string) get_permalink( $lp_demo_post ),
		);
	}
	$lp_listing_clock    = lp_format_runtime_clock( lp_tutorials_total_seconds( $lp_siblings ) );
	$lp_listing_mins     = lp_format_runtime_minutes( lp_tutorials_total_seconds( $lp_siblings ) );
	$lp_total_tutorials  = (int) ( wp_count_posts( 'lp_tutorial' )->publish ?? 0 );
	$lp_total_series     = count( lp_series_terms_nonempty() );
	$lp_values           = lp_tutorial_filter_values();
	$lp_category_options = lp_tutorial_category_filter_options();
	$lp_series_options   = lp_tutorial_series_filter_options();
	$lp_tag_options      = lp_tutorial_tag_filter_options();
	$lp_permalink        = (string) get_permalink( $lp_post_id );
	$lp_json_body        = lp_tutorial_transcript_body( (int) $lp_post_id, 'json' );
	$lp_srt_body         = lp_tutorial_transcript_body( (int) $lp_post_id, 'srt' );

	$lp_download_labels = array(
		'json' => 'Download JSON',
		'srt'  => 'Download SRT',
	);

	$lp_resources = array();
	if ( '' !== trim( $lp_json_body ) ) {
		$lp_resources[] = array(
			'title'          => 'Download transcript',
			'icon'           => 'icon-document-text',
			'meta'           => 'JSON',
			'kind'           => 'json',
			'href'           => (string) add_query_arg( 'lp_transcript', 'json', $lp_permalink ),
			'download_label' => $lp_download_labels['json'],
			'cues'           => lp_tutorial_transcript_cues( $lp_json_body, 'json' ),
			'pretty'         => lp_tutorial_transcript_pretty( $lp_json_body, 'json' ),
		);
	}
	if ( '' !== trim( $lp_srt_body ) ) {
		$lp_resources[] = array(
			'title'          => 'Captions · English',
			'icon'           => 'icon-globe-alt',
			'meta'           => 'SRT',
			'kind'           => 'srt',
			'href'           => (string) add_query_arg( 'lp_transcript', 'srt', $lp_permalink ),
			'download_label' => $lp_download_labels['srt'],
			'cues'           => lp_tutorial_transcript_cues( $lp_srt_body, 'srt' ),
			'pretty'         => lp_tutorial_transcript_pretty( $lp_srt_body, 'srt' ),
		);
	}

	$lp_board_rows = array();
	foreach ( $lp_siblings as $lp_i => $lp_sib ) {
		$lp_sib_clock = lp_format_runtime_clock( lp_tutorial_runtime_seconds( (int) $lp_sib->ID ) );
		$lp_sib_order = lp_tutorial_order_label( $lp_sib );
		if ( '' === $lp_sib_order ) {
			$lp_sib_order = sprintf( '%02d', $lp_i + 1 );
		}
		$lp_is_here = (int) $lp_sib->ID === (int) $lp_post_id;
		$lp_is_new  = ( time() - get_post_time( 'U', true, $lp_sib ) ) <= ( 30 * DAY_IN_SECONDS );
		$lp_board_rows[] = array(
			'part' => 'components/board-row',
			'args' => array(
				'time'             => '' !== $lp_sib_clock ? $lp_sib_clock : '—',
				'date_label'       => sprintf( 'LESSON %s', $lp_sib_order ),
				'title'            => get_the_title( $lp_sib ),
				'subtitle'         => get_the_excerpt( $lp_sib ),
				'location'         => $lp_move_name,
				'level'            => '',
				'location_icon_id' => 'icon-tag',
				'spaces'           => $lp_is_here ? 'NOW PLAYING' : ( $lp_is_new ? 'NEW' : 'WATCH' ),
				'tone'             => $lp_is_here ? 'now_playing' : ( $lp_is_new ? 'new' : 'available' ),
				'href'             => $lp_is_here ? '' : (string) get_permalink( $lp_sib ),
			),
		);
	}

	$lp_stage_meta_bits = array_filter(
		array(
			$lp_category_name ? strtoupper( $lp_category_name ) : '',
			$lp_subcategory_name ? strtoupper( $lp_subcategory_name ) : '',
		)
	);

	$lp_aside_rows = array_values(
		array_filter(
			array(
				$lp_series_term ? array( 'label' => 'SERIES', 'value' => $lp_series_term->name ) : null,
				$lp_category_name ? array( 'label' => 'CATEGORY', 'value' => $lp_category_name ) : null,
				$lp_subcategory_name ? array( 'label' => 'SUB-CATEGORY', 'value' => $lp_subcategory_name ) : null,
				'' !== $lp_order_label ? array( 'label' => 'ORDER', 'value' => sprintf( '%s of %d', $lp_order_label, $lp_lesson_total ) ) : null,
				'' !== $lp_clock ? array( 'label' => 'RUNTIME', 'value' => $lp_clock ) : null,
			)
		)
	);

	$lp_cta_label = $lp_listing_term instanceof WP_Term ? 'VIEW CATEGORY' : ( $lp_series_term ? 'VIEW SERIES' : 'ALL TUTORIALS' );
	$lp_cta_href  = $lp_listing_term instanceof WP_Term
		? ( '' !== $lp_subcategory_url ? $lp_subcategory_url : $lp_category_url )
		: $lp_series_url;

	get_header();
	?>

<main id="main">
	<?php
	$lp_crumbs = array(
		array(
			'label' => 'HOME',
			'href'  => home_url( '/' ),
		),
		array(
			'label' => 'TUTORIALS',
			'href'  => $lp_archive_url,
		),
	);
	if ( $lp_category_name ) {
		$lp_crumbs[] = array(
			'label' => strtoupper( $lp_category_name ),
			'href'  => $lp_category_url,
		);
	}
	if ( $lp_subcategory_name ) {
		$lp_crumbs[] = array(
			'label' => strtoupper( $lp_subcategory_name ),
			'href'  => $lp_subcategory_url,
		);
	} else {
		$lp_crumbs[] = array( 'label' => strtoupper( $lp_title ) );
	}

	lp_part(
		'components/breadcrumb-rail',
		array(
			'crumbs' => $lp_crumbs,
			'action' => array(
				'label' => 'ALL TUTORIALS ↗',
				'href'  => $lp_archive_url,
			),
		)
	);

	lp_part(
		'components/page-masthead',
		array(
			'title' => $lp_title,
			'note'  => $lp_excerpt
				? $lp_excerpt
				: ( $lp_series_term
					? sprintf( 'A lesson in the %s series.', $lp_series_term->name )
					: '' ),
		)
	);

	lp_part(
		'components/view-rail',
		array(
			'context'    => 'tutorials',
			'aria_label' => 'Tutorials view',
			'tabs'       => lp_tutorials_view_tabs( 'tutorial' ),
		)
	);

	lp_part(
		'components/filter-grid',
		array(
			'cells'  => array(
				array(
					'type'        => 'search',
					'key'         => 'Search',
					'name'        => 'tutorial_search',
					'placeholder' => sprintf( 'Search %d tutorials…', $lp_total_tutorials ),
					'value'       => $lp_values['tutorial_search'],
				),
				array(
					'type'    => 'select',
					'key'     => 'Category',
					'name'    => 'tutorial_category',
					'options' => $lp_category_options,
					'value'   => $lp_values['tutorial_category'],
				),
				array(
					'type'    => 'select',
					'key'     => 'Series',
					'name'    => 'tutorial_series',
					'options' => $lp_series_options,
					'value'   => $lp_values['tutorial_series'],
				),
				array(
					'type'    => 'select',
					'key'     => 'Tag',
					'name'    => 'tutorial_tag',
					'options' => $lp_tag_options,
					'value'   => $lp_values['tutorial_tag'],
				),
			),
			'action' => $lp_archive_url,
			'submit' => 'Apply tutorial filters',
		)
	);
	?>

	<div class="w-full bg-base-100" data-section="now-playing">
		<div class="px-6 lg:px-16 py-scale-2xl flex flex-col gap-[26px]">
			<?php lp_part( 'elements/rule', array( 'tone' => 'hairline' ) ); ?>
			<div class="flex flex-col lg:flex-row gap-[32px] items-start">
				<div class="flex-1 min-w-0 self-stretch">
					<?php
					lp_part(
						'components/video-stage',
						array(
							'image_id'       => $lp_thumb_id,
							'status_label'   => '' !== $lp_order_label
								? sprintf( 'NOW PLAYING · LESSON %s', $lp_order_label )
								: 'NOW PLAYING',
							'quality_label'  => $lp_clock ? 'EN · HD · ' . $lp_clock : 'EN · HD',
							'badge_label'    => $lp_move_name && '' !== $lp_order_label
								? sprintf( '%s · LESSON %s OF %02d', strtoupper( $lp_move_name ), $lp_order_label, $lp_lesson_total )
								: ( $lp_move_name
									? strtoupper( $lp_move_name )
									: ( '' !== $lp_order_label
										? sprintf( 'LESSON %s OF %02d', $lp_order_label, $lp_lesson_total )
										: 'DEMONSTRATION' ) ),
							'duration_label' => $lp_clock,
							'title'          => $lp_title,
							'stage_meta'     => implode( ' · ', $lp_stage_meta_bits ),
							'time_label'     => $lp_clock ? '00:00 / ' . $lp_clock : '',
							'up_next_label'  => $lp_next_post
								? 'UP NEXT — ' . get_the_title( $lp_next_post )
								: '',
							'progress'       => 0,
							'command'        => '' !== $lp_video_id ? 'show-modal' : '',
							'command_for'    => '' !== $lp_video_id ? $lp_video_dlg : '',
							'data_attrs'     => '' !== $lp_video_id
								? array(
									'data-video-type' => 'youtube',
									'data-video-id'   => $lp_video_id,
									'data-autoplay'   => 'true',
								)
								: array(),
						)
					);
					?>
				</div>
				<div class="w-full lg:w-[340px] shrink-0 flex flex-col gap-[24px]">
					<?php
					lp_part(
						'components/aside-panel',
						array(
							'title'      => 'THIS TUTORIAL',
							'spots_left' => '' !== $lp_order_label
								? sprintf( 'LESSON %s / %d', $lp_order_label, $lp_lesson_total )
								: sprintf( '%d VIDEOS', $lp_lesson_total ),
							'rows'       => $lp_aside_rows,
							'cta_label'  => $lp_cta_label,
							'href'       => $lp_cta_href,
							'note'       => 'Free to watch. No account needed. New tutorials added every month.',
							'surface'    => 'page',
						)
					);
					?>
					<?php if ( $lp_resources ) : ?>
						<div class="flex flex-col gap-[12px]" data-mount="resources">
							<div class="flex items-center justify-between gap-3 pb-2.5 border-b border-base-300">
								<span class="font-label text-[10px] font-semibold uppercase tracking-[1px] text-base-content">RESOURCES</span>
								<span class="font-label text-[10px] font-normal text-base-content/65"><?php echo esc_html( sprintf( '%02d', count( $lp_resources ) ) ); ?></span>
							</div>
							<ul role="list" class="flex flex-col w-full m-0 p-0 list-none">
								<?php foreach ( $lp_resources as $lp_resource ) : ?>
									<li>
										<details class="collapse collapse-arrow rounded-none border-b border-base-300" data-component="transcript-resource">
											<summary class="collapse-title min-h-0 py-[13px] px-[16px] sm:px-[22px] flex items-center gap-[14px] bg-base-100 hover:bg-base-200 transition-colors duration-150 text-left cursor-pointer">
												<?php if ( '' !== (string) $lp_resource['icon'] ) : ?>
													<span class="text-base-content/65 shrink-0" aria-hidden="true"><?php lp_icon( (string) $lp_resource['icon'], 'w-3.5 h-3.5' ); ?></span>
												<?php endif; ?>
												<span class="flex-1 min-w-0 flex flex-col gap-[5px]">
													<span class="font-heading text-[15px] font-medium tracking-[-0.2px] text-base-content truncate"><?php echo esc_html( (string) $lp_resource['title'] ); ?></span>
													<?php if ( '' !== (string) $lp_resource['meta'] ) : ?>
														<span class="font-label text-[10px] font-normal tracking-[0.6px] uppercase text-base-content/65 truncate"><?php echo esc_html( (string) $lp_resource['meta'] ); ?></span>
													<?php endif; ?>
												</span>
											</summary>
											<div class="collapse-content px-[16px] sm:px-[22px]">
												<div class="flex items-center justify-between gap-3 pb-3 mb-3 border-b border-base-300">
													<?php
													lp_part(
														'elements/text-link',
														array(
															'label'   => (string) $lp_resource['download_label'],
															'href'    => (string) $lp_resource['href'],
															'variant' => 'page_accent',
														)
													);
													?>
												</div>
												<?php if ( ! empty( $lp_resource['cues'] ) ) : ?>
													<div class="max-h-80 overflow-y-auto flex flex-col gap-4 py-1">
														<?php foreach ( $lp_resource['cues'] as $lp_cue ) : ?>
															<?php
															lp_part(
																'components/transcript-line',
																array(
																	'timestamp' => (string) ( $lp_cue['clock'] ?? '' ),
																	'text'      => (string) ( $lp_cue['text'] ?? '' ),
																	'surface'   => 'page',
																)
															);
															?>
														<?php endforeach; ?>
													</div>
												<?php else : ?>
													<pre class="m-0 font-body text-[13px] font-normal leading-[1.6] tracking-[0.1px] text-base-content/80 whitespace-pre-wrap break-words max-h-80 overflow-y-auto"><?php echo esc_html( (string) $lp_resource['pretty'] ); ?></pre>
												<?php endif; ?>
											</div>
										</details>
									</li>
								<?php endforeach; ?>
							</ul>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>

	<div class="w-full bg-neutral" data-section="series">
		<div class="px-6 lg:px-16 py-scale-2xl flex flex-col gap-[20px]">
			<?php
			lp_part(
				'components/meta-row',
				array(
					'left'    => $lp_listing_term instanceof WP_Term ? '02 — THE CATEGORY' : '02 — THE SERIES',
					'right'   => sprintf(
						'%d VIDEOS%s',
						$lp_lesson_total,
						$lp_listing_mins ? ' · ' . $lp_listing_mins : ( $lp_listing_clock ? ' · ' . $lp_listing_clock : '' )
					),
					'surface' => 'board',
				)
			);
			lp_part( 'elements/rule', array( 'tone' => 'board' ) );
			lp_part(
				'components/board-shell',
				array(
					'board_title' => $lp_listing_term instanceof WP_Term
						? strtoupper( $lp_listing_term->name ) . ' — LESSON BOARD'
						: ( $lp_series_term ? strtoupper( $lp_series_term->name ) . ' — LESSON BOARD' : 'LESSON BOARD' ),
					'columns'     => array( 'RUNTIME', 'LESSON', 'MOVE', 'LEVEL', 'STATUS' ),
					'rows'        => $lp_board_rows,
					'foot_left'   => $lp_listing_term instanceof WP_Term
						? 'VIEW CATEGORY →'
						: ( $lp_series_term ? 'VIEW SERIES →' : '' ),
					'foot_href'   => $lp_cta_href,
					'foot_right'  => sprintf( '%d TUTORIALS · %d SERIES · FREE TO WATCH', $lp_total_tutorials, $lp_total_series ),
				)
			);
			?>
		</div>
	</div>

	<?php if ( $lp_body || $lp_takeaways || $lp_closing || $lp_has_copy || $lp_summary_paras ) : ?>
	<div class="w-full bg-base-100" data-section="video-details">
		<div class="px-6 lg:px-16 py-scale-2xl flex flex-col gap-[32px]">
			<?php
			lp_part(
				'components/meta-row',
				array(
					'left'    => 'VIDEO DETAILS',
					'right'   => '',
					'surface' => 'page',
				)
			);
			lp_part( 'elements/rule', array( 'tone' => 'hairline' ) );
			?>
			<?php
			$lp_details_main   = $lp_body || $lp_has_copy || $lp_summary_paras;
			$lp_details_layout = array(
				'split' => 'grid lg:grid-cols-2 gap-[32px] lg:gap-[56px] items-start',
				'stack' => 'flex flex-col gap-[32px]',
			);
			$lp_layout_key     = ( $lp_details_main && $lp_takeaways ) ? 'split' : 'stack';
			?>
			<div class="<?php echo esc_attr( $lp_details_layout[ $lp_layout_key ] ); ?>">
				<?php if ( $lp_details_main ) : ?>
					<div class="flex flex-col gap-[32px] min-w-0">
						<?php if ( $lp_body ) : ?>
							<div class="grid sm:grid-cols-2 gap-[32px]">
								<?php foreach ( $lp_body as $lp_para ) : ?>
									<div class="flex flex-col gap-[10px]">
										<?php
										lp_part(
											'elements/glyph-label',
											array(
												'label'   => (string) ( $lp_para['index'] ?? '' ),
												'surface' => 'page',
												'tone'    => 'muted',
											)
										);
										?>
										<p class="m-0 font-body text-[13px] leading-[1.6] text-base-content/65"><?php echo esc_html( (string) ( $lp_para['text'] ?? '' ) ); ?></p>
									</div>
								<?php endforeach; ?>
							</div>
						<?php elseif ( $lp_has_copy ) : ?>
							<p class="m-0 font-body text-[13px] leading-[1.6] text-base-content/65"><?php echo esc_html( $lp_raw_content ); ?></p>
						<?php endif; ?>

						<?php if ( $lp_summary_paras ) : ?>
							<div class="flex flex-col gap-[16px]">
								<div class="flex items-center justify-between gap-3 pb-2.5 border-b border-base-300">
									<span class="font-label text-[10px] font-semibold uppercase tracking-[1px] text-base-content">SUMMARY</span>
								</div>
								<div class="flex flex-col gap-[14px]">
									<?php foreach ( $lp_summary_paras as $lp_summary_para ) : ?>
										<p class="m-0 font-body text-[13px] leading-[1.6] text-base-content/65"><?php echo wp_kses_post( lp_blog_inline_markdown( $lp_summary_para ) ); ?></p>
									<?php endforeach; ?>
									<?php if ( $lp_ai_note ) : ?>
										<p class="m-0 font-label text-[10px] font-normal text-base-content/65"><?php echo esc_html( $lp_ai_note ); ?></p>
									<?php endif; ?>
								</div>
							</div>
						<?php endif; ?>
					</div>
				<?php endif; ?>

				<?php if ( $lp_takeaways ) : ?>
					<div class="flex flex-col gap-[16px]">
						<div class="flex items-center justify-between gap-3 pb-2.5 border-b border-base-300">
							<span class="font-label text-[10px] font-semibold uppercase tracking-[1px] text-base-content">KEY TAKEAWAYS</span>
							<span class="font-label text-[10px] font-normal text-base-content/65"><?php echo esc_html( sprintf( '%02d', count( $lp_takeaways ) ) ); ?></span>
						</div>
						<ul role="list" class="flex flex-col gap-[14px] m-0 p-0 list-none">
							<?php foreach ( $lp_takeaways as $lp_t ) : ?>
								<li>
									<?php
									lp_part(
										'components/checklist-item',
										array(
											'text' => is_array( $lp_t ) ? (string) ( $lp_t['text'] ?? '' ) : (string) $lp_t,
										)
									);
									?>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>
			</div>

			<?php if ( $lp_closing ) : ?>
				<?php lp_part( 'elements/rule', array( 'tone' => 'ink' ) ); ?>
				<div class="flex flex-col gap-[10px]">
					<p class="font-body text-[24px] leading-[1.4] text-base-content"><?php echo esc_html( $lp_closing ); ?></p>
					<?php if ( $lp_ai_note ) : ?>
						<p class="font-label text-[10px] font-normal text-base-content/65"><?php echo esc_html( $lp_ai_note ); ?></p>
					<?php endif; ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
	<?php endif; ?>

	<?php if ( $lp_demos ) : ?>
	<div class="w-full bg-base-100" data-section="demonstrations">
		<div class="px-6 lg:px-16 py-scale-2xl flex flex-col gap-[32px]">
			<?php
			lp_part( 'elements/rule', array( 'tone' => 'hairline' ) );
			lp_part(
				'components/section-head',
				array(
					'heading' => 'Two demonstrations.',
					'note'    => 'The same movement at full speed.',
					'surface' => 'page',
				)
			);
			?>
			<div class="grid sm:grid-cols-2 gap-[24px]">
				<?php foreach ( $lp_demos as $lp_demo ) : ?>
					<?php
					lp_part(
						'components/video-card',
						array(
							'variant'    => 'compact',
							'image_id'   => (int) ( $lp_demo['image_id'] ?? 0 ),
							'kicker'     => (string) ( $lp_demo['kicker'] ?? '' ),
							'title'      => (string) ( $lp_demo['title'] ?? '' ),
							'meta'       => (string) ( $lp_demo['meta'] ?? '' ),
							'foot_label' => (string) ( $lp_demo['foot_label'] ?? '' ),
							'note'       => (string) ( $lp_demo['note'] ?? '' ),
							'href'       => (string) ( $lp_demo['href'] ?? '' ),
						)
					);
					?>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
	<?php endif; ?>

	<?php
	lp_render_block( 'train_in_person', array() );

	lp_part(
		'components/page-onward',
		array(
			'prev' => array(
				'keyword' => '← THE SERIES',
				'label'   => $lp_series_term ? 'Back to ' . $lp_series_term->name : 'Back to tutorials',
				'href'    => $lp_series_url,
			),
			'next' => $lp_next_post
				? array(
					'keyword' => 'NEXT LESSON →',
					'label'   => get_the_title( $lp_next_post ),
					'href'    => (string) get_permalink( $lp_next_post ),
				)
				: array(
					'keyword' => 'TRAIN IN PERSON →',
					'label'   => 'Book a class',
					'href'    => (string) get_post_type_archive_link( lp_class_post_type() ),
				),
		)
	);
	?>

	<?php
	if ( '' !== $lp_video_id ) {
		lp_part(
			'elements/dialog-video',
			array(
				'dialog_id'  => $lp_video_dlg,
				'video_type' => 'youtube',
				'title'      => $lp_title,
			)
		);
	}
	?>
</main>

	<?php
endwhile;

get_footer();
